# Generated by Django 4.0.6 on 2022-08-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0006_gamer_delete_pc_gamer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gamer',
        ),
    ]
