# Generated by Django 4.0.6 on 2022-08-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0004_pcgamer_delete_pc_gamer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pcgamer',
            new_name='pc_gamer',
        ),
    ]
