# Generated by Django 4.0.6 on 2022-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0008_pc_gamer'),
    ]

    operations = [
        migrations.CreateModel(
            name='smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.CharField(max_length=10)),
                ('type_processeur', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('rom', models.CharField(max_length=100)),
                ('systeme_exploitation', models.CharField(max_length=100)),
                ('ecran_size', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
                ('store', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=500)),
            ],
        ),
    ]
