# Generated by Django 4.0.6 on 2022-08-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0009_smartphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='type_processeur',
        ),
    ]
